"""Add due_date and priority to Task model

Revision ID: 72f197c2a319
Revises: a5efa387a97b
Create Date: 2025-07-08 10:54:28.038874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '72f197c2a319'
down_revision: Union[str, None] = 'a5efa387a97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the columns as nullable
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'normal', 'high', name='priorityenum'), nullable=True))
    
    # Update existing records with default values
    op.execute(text("UPDATE tasks SET due_date = created_at, priority = 'normal'"))
    
    # Then alter the columns to make them not nullable
    op.alter_column('tasks', 'due_date', nullable=False)
    op.alter_column('tasks', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
